inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - bin/**
  NewCops: enable

# These are boilerplate, except maybe the migrations, but those already happened
Style/Documentation:
  Exclude:
    - 'app/models/application_record.rb'
    - 'config/application.rb'

# auto_annotate_models is boilerplate, spec causes problems
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'lib/tasks/auto_annotate_models.rake'

# Ruby 3 does this
Style/FrozenStringLiteralComment:
  Enabled: false

# Feel like I shouldn't mess with this file
Rails/FilePath:
  Exclude:
    - 'config/environments/development.rb'
