inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - bin/**
  NewCops: enable

# These are boilerplate, except maybe the migrations, but those already happened
Style/Documentation:
  Exclude:
    - 'app/models/application_record.rb'
    - 'config/application.rb'

# auto_annotate_models is boilerplate, spec causes problems
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'lib/tasks/auto_annotate_models.rake'

# Ruby 3 does this
Style/FrozenStringLiteralComment:
  Enabled: false

# Feel like I shouldn't mess with this file
Rails/FilePath:
  Exclude:
    - 'config/environments/development.rb'

# I didn't make it, I ain't letting rubocop touch it
Style/RedundantFetchBlock:
  Exclude:
    - 'config/puma.rb'

# encourages overuse of let, allegedly
RSpec/ExampleLength:
  Enabled: false

# this seems like overkill
RSpec/MultipleExpectations:
  Enabled: false

# because using shoulda matchers
RSpec/ImplicitExpect:
  EnforcedStyle: should

# I think this is a good idea to fix, but seems a lil unsafe to do
Style/GlobalStdStream:
  Exclude:
    - 'config/environments/production.rb'

# I don't understand why I should make changes to a migration I already ran
# Furthermore, I feel like this rule will likely not catch problems before I
# run the migration
Rails/BulkChangeTable:
  Exclude:
    - 'db/migrate/20210309210115_change_students_column_values.rb'
