inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec


AllCops:
  Exclude:
    - bin/**
  NewCops: enable

Style/Documentation:
  Exclude:
    - 'app/models/application_record.rb'
    - 'config/application.rb'
    - 'db/migrate/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'lib/tasks/auto_annotate_models.rake'
